ALTER TABLE slots DROP COLUMN IF EXISTS enabled;
ALTER TABLE slots DROP COLUMN IF EXISTS presence;

ALTER TABLE keys DROP COLUMN IF EXISTS requires_approval;
ALTER TABLE keys DROP COLUMN IF EXISTS enabled;
ALTER TABLE keys DROP COLUMN IF EXISTS description;
ALTER TABLE keys DROP COLUMN IF EXISTS building;
ALTER TABLE keys DROP COLUMN IF EXISTS room_no;

ALTER TABLE devices DROP COLUMN IF EXISTS ip_address;
