-- Sprint 4.3：补齐 Key / Device / Slot 查询契约所需字段。

ALTER TABLE devices ADD COLUMN IF NOT EXISTS ip_address VARCHAR(100);

ALTER TABLE keys ADD COLUMN IF NOT EXISTS room_no VARCHAR(50) NOT NULL DEFAULT '';
ALTER TABLE keys ADD COLUMN IF NOT EXISTS building VARCHAR(100) NOT NULL DEFAULT '';
ALTER TABLE keys ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE keys ADD COLUMN IF NOT EXISTS enabled BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE keys ADD COLUMN IF NOT EXISTS requires_approval BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE slots ADD COLUMN IF NOT EXISTS presence VARCHAR(20);
ALTER TABLE slots ADD COLUMN IF NOT EXISTS enabled BOOLEAN NOT NULL DEFAULT TRUE;

-- 旧版 slots.status 只有 EMPTY 等粗粒度值；根据已绑定钥匙的业务状态初始化物理在位状态。
UPDATE slots AS s
SET presence = CASE
    WHEN EXISTS (
        SELECT 1
        FROM keys AS k
        WHERE k.slot_id = s.id
          AND k.status NOT IN ('BORROWED', 'OVERDUE')
    ) THEN 'PRESENT'
    ELSE 'ABSENT'
END
WHERE s.presence IS NULL;

ALTER TABLE slots ALTER COLUMN presence SET DEFAULT 'UNKNOWN';
ALTER TABLE slots ALTER COLUMN presence SET NOT NULL;
