/**
 * 智能钥匙柜系统全局标准错误码定义
 */
export enum OperationErrorCode {
  // ================= 认证与权限 (AUTH) =================
  AUTH_FAILED = 'AUTH_FAILED',
  AUTH_FACE_FAILED = 'AUTH_FACE_FAILED',
  AUTH_LIVENESS_FAILED = 'AUTH_LIVENESS_FAILED',
  AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED',

  // ================= 预约业务 (RESERVATION) =================
  RESERVATION_NOT_FOUND = 'RESERVATION_NOT_FOUND',
  RESERVATION_EXPIRED = 'RESERVATION_EXPIRED',
  RESERVATION_CONFLICT = 'RESERVATION_CONFLICT',
  RESERVATION_NOT_ACTIVE = 'RESERVATION_NOT_ACTIVE',
  RESERVATION_ALREADY_USED = 'RESERVATION_ALREADY_USED',

  // ================= 钥匙与槽位 (KEY / SLOT) =================
  KEY_NOT_FOUND = 'KEY_NOT_FOUND',
  KEY_NOT_AVAILABLE = 'KEY_NOT_AVAILABLE',
  KEY_NOT_PRESENT = 'KEY_NOT_PRESENT',
  KEY_ALREADY_BORROWED = 'KEY_ALREADY_BORROWED',
  KEY_WRONG_RETURN = 'KEY_WRONG_RETURN',
  KEY_DISABLED = 'KEY_DISABLED',
  SLOT_NOT_FOUND = 'SLOT_NOT_FOUND',
  SLOT_DISABLED = 'SLOT_DISABLED',

  // ================= 设备状态 (DEVICE) =================
  DEVICE_NOT_FOUND = 'DEVICE_NOT_FOUND',
  DEVICE_OFFLINE = 'DEVICE_OFFLINE',
  DEVICE_BUSY = 'DEVICE_BUSY',
  DEVICE_FAULT = 'DEVICE_FAULT',

  // ================= 机械与执行机构 (MOTOR / DOOR) =================
  MOTOR_POSITION_FAILED = 'MOTOR_POSITION_FAILED',
  MOTOR_HOME_FAILED = 'MOTOR_HOME_FAILED',
  DOOR_OPEN_FAILED = 'DOOR_OPEN_FAILED',
  DOOR_CLOSE_FAILED = 'DOOR_CLOSE_FAILED',
  DOOR_NOT_CLOSED = 'DOOR_NOT_CLOSED',
  KEY_NOT_REMOVED = 'KEY_NOT_REMOVED',

  // ================= 射频识别 (RFID) =================
  RFID_NOT_FOUND = 'RFID_NOT_FOUND',
  RFID_WRONG_KEY = 'RFID_WRONG_KEY',
  RFID_READ_TIMEOUT = 'RFID_READ_TIMEOUT',

  // ================= 设备操作生命周期 (OPERATION) =================
  OPERATION_NOT_FOUND = 'OPERATION_NOT_FOUND',
  OPERATION_TIMEOUT = 'OPERATION_TIMEOUT',
  OPERATION_DUPLICATED = 'OPERATION_DUPLICATED',
  OPERATION_STATE_CONFLICT = 'OPERATION_STATE_CONFLICT',
  OPERATION_USER_MISMATCH = 'OPERATION_USER_MISMATCH',

  // ================= 系统与网络 (SYSTEM / NETWORK) =================
  NETWORK_ERROR = 'NETWORK_ERROR',
  SYSTEM_ERROR = 'SYSTEM_ERROR',
}
